name: Announcement
description: "[Anthropic team only] Post an announcement about MCP changes"
labels: ["announcement"]
body:
  - type: markdown
    attributes:
      value: |
        **This template is for Anthropic team members to post announcements.**

        For bug reports or feature requests, please use the other templates.

  - type: input
    id: title
    attributes:
      label: Summary
      description: A brief summary of the change
      placeholder: e.g., SSE transport deprecation timeline
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Breaking Change
        - Deprecation
        - New Feature
        - Security
        - Maintenance
    validations:
      required: true

  - type: input
    id: timeline
    attributes:
      label: Timeline
      description: When does this take effect?
      placeholder: e.g., Rolling out week of Jan 15, 2025
    validations:
      required: false

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Full details about the change
    validations:
      required: true

  - type: textarea
    id: action
    attributes:
      label: Action Required
      description: What do developers need to do?
      placeholder: |
        - Update your MCP server to...
        - No action required
    validations:
      required: true

  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Links to documentation, migration guides, etc.
    validations:
      required: false
